//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarName
    {
        public int CarNameID { get; set; }
        public string CarName1 { get; set; }
        public int WorkshopCategoryID { get; set; }
    
        public virtual CompanyName CompanyName { get; set; }
    }
}
