//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryProductHome
    {
        public int CategoryProductHomeID { get; set; }
        public string CategoryProductHomeName { get; set; }
        public int CategoryProductID { get; set; }
    }
}
