//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int Id { get; set; }
        public string order_id { get; set; }
        public string Pname { get; set; }
        public Nullable<decimal> Pprice { get; set; }
        public Nullable<int> Pqty { get; set; }
        public string Pimage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DateBuy { get; set; }
        public Nullable<int> WorkshopID { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual WorkShopR WorkShopR { get; set; }
    }
}
