//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public string Model { get; set; }
        public string Deatalis { get; set; }
        public string Image { get; set; }
        public string CompanyName { get; set; }
        public string CarName { get; set; }
        public int WorkshopID { get; set; }
        public int CategoryProduct { get; set; }
        public int CompanyID { get; set; }
        public int CarNameID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual WorkShopR WorkShopR { get; set; }
    }
}
